
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.table.AbstractTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;


public class ingridients_nutrients extends javax.swing.JFrame {

    /**
     * Creates new form ingridients_nutrients
     */
    String name;
    long id;
    ArrayList<ingredient_nutrients> al;
    mytablemodel tm;
    public ingridients_nutrients(String Name, long ID) {
        initComponents();
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setSize(d.width, d.height);
        photolb.setBounds(0, 0, d.width, d.height);
        ImageIcon i1 = new ImageIcon("src/uploads/slider12.jpg");
        Image img = i1.getImage().getScaledInstance(d.width, d.height, Image.SCALE_SMOOTH);
        photolb.setIcon(new ImageIcon(img));
        name = Name;
        id = ID;
        al = new ArrayList<>();
        tm = new mytablemodel();
        jTable1.setModel(tm);
        getIngredientInformation();
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
    }

    class mytablemodel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return al.size();
        }

        @Override
        public int getColumnCount() {
            return 4;
        }

        @Override
        public String getColumnName(int j) {
            String i[] = {"name", "amount", "unit", "percentage(daily need"};
            return i[j];
        }

        @Override
        public Object getValueAt(int i, int j) {
            ingredient_nutrients ig = al.get(i);
            if (j == 0) {
                return ig.name;
            } else if (j == 1) {
                return ig.amount1;
            } else if (j == 2) {
                return ig.unit;
            } else{
                return ig.percentage;
            }
        }

    }

    void getIngredientInformation() {
        try {
            HttpResponse<String> response = Unirest.get("https://spoonacular-recipe-food-nutrition-v1.p.rapidapi.com/food/ingredients/" + id + "/information?amount=150&unit=grams")
                    .header("X-RapidAPI-Key", "652fb35be6msh43c979dd6e258dap1ede35jsn29e136726656")
                    .header("X-RapidAPI-Host", "spoonacular-recipe-food-nutrition-v1.p.rapidapi.com")
                    .asString();
            if (response.getStatus() == 200) {
                String ans = response.getBody();
                JSONParser parser = new JSONParser();
                System.out.println(ans);
                JSONObject jsonObject = (JSONObject) parser.parse(ans);
                double amount = (double) jsonObject.get("amount");
                String unit = (String) jsonObject.get("unit");
                jname.setText("Name :"+name);
                String consistency = (String) jsonObject.get("consistency");
                jamount.setText("Amount :"+amount + "");
                junit.setText("Unit :"+unit);
                jconsistency.setText("Consistency :"+consistency);
                JSONObject jo = (JSONObject) jsonObject.get("nutrition");
                JSONArray ja = (JSONArray) jo.get("nutrients");
                for (int i = 0; i < ja.size(); i++) {
                    JSONObject jo2 = (JSONObject) ja.get(i);
                    String name = (String) jo2.get("name");
                    double amount1 = (double) jo2.get("amount");
                    String unit1 = (String) jo2.get("unit");
                    double percentage = (double) jo2.get("percentOfDailyNeeds");
                    System.out.println(name + " " + unit1 + " " + amount1 + " " + percentage);
                    al.add(new ingredient_nutrients(name, amount1, unit, percentage));
                }
                tm.fireTableDataChanged();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jname = new javax.swing.JLabel();
        jamount = new javax.swing.JLabel();
        junit = new javax.swing.JLabel();
        jconsistency = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        photolb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingredients Nutrients");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(530, 120, 300, 40);

        jname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jname.setForeground(new java.awt.Color(255, 255, 255));
        jname.setText("jLabel2");
        getContentPane().add(jname);
        jname.setBounds(500, 180, 280, 30);

        jamount.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jamount.setForeground(new java.awt.Color(255, 255, 255));
        jamount.setText("jLabel3");
        getContentPane().add(jamount);
        jamount.setBounds(500, 230, 280, 30);

        junit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        junit.setForeground(new java.awt.Color(255, 255, 255));
        junit.setText("jLabel4");
        getContentPane().add(junit);
        junit.setBounds(500, 280, 280, 30);

        jconsistency.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jconsistency.setForeground(new java.awt.Color(255, 255, 255));
        jconsistency.setText("jLabel5");
        getContentPane().add(jconsistency);
        jconsistency.setBounds(500, 330, 280, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 400, 530, 290);

        photolb.setText("jLabel2");
        getContentPane().add(photolb);
        photolb.setBounds(50, 10, 37, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingridients_nutrients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingridients_nutrients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingridients_nutrients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingridients_nutrients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingridients_nutrients("", 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jamount;
    private javax.swing.JLabel jconsistency;
    private javax.swing.JLabel jname;
    private javax.swing.JLabel junit;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
