
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import vmm.DBLoader;
import java.sql.*;


public class user_signup extends javax.swing.JFrame {


    File f;
    JFileChooser jfc;
    String path;

    public user_signup() {
        initComponents();
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setSize(d.width, d.height);
        photolb1.setBounds(0, 0, d.width, d.height);
        ImageIcon i1 = new ImageIcon("src/uploads/slider12.jpg");
        Image img = i1.getImage().getScaledInstance(d.width, d.height, Image.SCALE_SMOOTH);
        photolb1.setIcon(new ImageIcon(img));
        jButton1.setBackground(Color.white);
        jButton2.setBackground(Color.white);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("User Signup");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jusername = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jmobile = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jpassword = new javax.swing.JPasswordField();
        jconfirmpassword = new javax.swing.JPasswordField();
        photolb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO NUTRITION HUB");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(520, 140, 380, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 270, 90, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(740, 270, 60, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mobile No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 340, 80, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(740, 340, 80, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Confirm Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 430, 110, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(740, 420, 80, 16);

        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(740, 500, 390, 40);

        jusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusernameActionPerformed(evt);
            }
        });
        getContentPane().add(jusername);
        jusername.setBounds(490, 260, 190, 40);
        getContentPane().add(jemail);
        jemail.setBounds(930, 260, 190, 40);

        jmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmobileActionPerformed(evt);
            }
        });
        getContentPane().add(jmobile);
        jmobile.setBounds(490, 330, 190, 40);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Photo");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 510, 100, 16);

        photolb.setForeground(new java.awt.Color(255, 255, 255));
        photolb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(photolb);
        photolb.setBounds(660, 610, 200, 100);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SIGNUP");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(650, 190, 140, 40);

        buttonGroup1.add(rb1);
        rb1.setForeground(new java.awt.Color(255, 255, 255));
        rb1.setText("Male");
        getContentPane().add(rb1);
        rb1.setBounds(950, 410, 70, 30);

        buttonGroup1.add(rb2);
        rb2.setForeground(new java.awt.Color(255, 255, 255));
        rb2.setText("Female");
        getContentPane().add(rb2);
        rb2.setBounds(1020, 410, 80, 30);

        jButton2.setText("Browse....");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(490, 500, 190, 40);
        getContentPane().add(jpassword);
        jpassword.setBounds(930, 330, 190, 40);
        getContentPane().add(jconfirmpassword);
        jconfirmpassword.setBounds(490, 410, 190, 40);

        photolb1.setText("jLabel9");
        getContentPane().add(photolb1);
        photolb1.setBounds(0, 0, 37, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = jusername.getText();
        String email = jemail.getText();
//        System.out.println(email);
        String mobile_no = jmobile.getText();
        String password = jpassword.getText();
        String confirm_password = jconfirmpassword.getText();
        String gender;
        if (rb1.isSelected()) {
            gender = "male";
        } else {
            gender = "female";
        }

        if (username.isEmpty() || email.isEmpty() || mobile_no.isEmpty() || password.isEmpty() || confirm_password.isEmpty() || gender.isEmpty()) {
            JOptionPane.showMessageDialog(this, "all the fields are required");
        } else if (f == null) {
            JOptionPane.showMessageDialog(this, "Please choose a Photo");
        } else if (email.indexOf("@") == -1 || email.indexOf(".") == -1) {
            JOptionPane.showMessageDialog(this, "Please enter  valid Email");
        } else if (mobile_no.length() != 10) {
            JOptionPane.showMessageDialog(this, "Please enter valid Mobile number(length 10)");
        } else if (!password.equals(confirm_password)) {
            JOptionPane.showMessageDialog(this, "Password and Confirm Password must be same");
        } else {
            try {
                ResultSet rs = DBLoader.exexuteSQL("select * from user where email='"+email+"' ");
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "User lready Exist");
                } else {
                    String pic = savefile.savefile(path);
                    rs.moveToInsertRow();
                    rs.updateString("email", email);
                    rs.updateString("username", username);
                    rs.updateString("mobile_no", mobile_no);
                    rs.updateString("password", password);
                    rs.updateString("gender", gender);
                    rs.updateString("photo", pic);
                    rs.insertRow();
                    JOptionPane.showMessageDialog(this, "Signup Successful!!");
                    dispose();
                    user_login obj = new user_login();
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jfc = new JFileChooser("C://");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png");
        jfc.setFileFilter(filter);
        int ans = jfc.showOpenDialog(this);

        if (ans == JFileChooser.APPROVE_OPTION) {
            f = jfc.getSelectedFile();
            path = f.getPath();
            ImageIcon ic = new ImageIcon(path);
            Image img = ic.getImage().getScaledInstance(photolb.getWidth(), photolb.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon ic1 = new ImageIcon(img);
            photolb.setIcon(ic1);
        } else {
            JOptionPane.showMessageDialog(this, "Cancelled!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusernameActionPerformed

    private void jmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmobileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jconfirmpassword;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jmobile;
    private javax.swing.JPasswordField jpassword;
    private javax.swing.JTextField jusername;
    private javax.swing.JLabel photolb;
    private javax.swing.JLabel photolb1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    // End of variables declaration//GEN-END:variables
}
