import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.*;
import vmm.DBLoader;


public class user_forgot_password extends javax.swing.JFrame {

    String email;
    String otp;

    public user_forgot_password() {
        initComponents();
        jPanel1.setBounds(473, 319, 420, 130);
        jPanel2.setBounds(473, 319, 420, 130);
        jPanel3.setBounds(473, 319, 420, 150);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        Dimension d = new Dimension(Toolkit.getDefaultToolkit().getScreenSize());
        setSize(d.width, d.height);
        photolb.setBounds(0, 0, d.width, d.height);
        ImageIcon i1 = new ImageIcon("src/uploads/slider12.jpg");
        Image img = i1.getImage().getScaledInstance(d.width, d.height, Image.SCALE_SMOOTH);
        photolb.setIcon(new ImageIcon(img));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Forgot Password");
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jotp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jnewpassword = new javax.swing.JTextField();
        jconfirmpassword = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        photolb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Enter Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 200, 30);

        jLabel7.setText("Email");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 50, 80, 16);
        jPanel1.add(jemail);
        jemail.setBounds(200, 50, 150, 22);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Generate otp");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 90, 120, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(520, 310, 420, 130);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel2.setText("Enter otp");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(50, 50, 120, 20);

        jotp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jotpActionPerformed(evt);
            }
        });
        jPanel2.add(jotp);
        jotp.setBounds(200, 50, 150, 22);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setText("Otp Verification");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(113, 10, 240, 28);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Proceed");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(140, 90, 130, 22);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(520, 460, 420, 120);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Set New Password");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(120, 10, 210, 30);

        jLabel4.setText("New Password");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 60, 140, 16);

        jLabel5.setText("Confirm New password");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(50, 90, 150, 16);
        jPanel3.add(jnewpassword);
        jnewpassword.setBounds(260, 50, 130, 22);
        jPanel3.add(jconfirmpassword);
        jconfirmpassword.setBounds(260, 90, 130, 22);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(140, 120, 140, 22);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(520, 600, 420, 150);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("USER FORGOT PASSWORD");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(530, 220, 340, 30);

        photolb.setText("jLabel9");
        getContentPane().add(photolb);
        photolb.setBounds(0, 0, 37, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jotpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jotpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jotpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        email = jemail.getText();
        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter an email");
        } else {
            try {
                ResultSet rs = DBLoader.exexuteSQL("select * from user where email='"+email+"' ");
                if(rs.next()){
                    int onetimepass = (int) (1000+(9999-1000)*Math.random());
                    otp = String.valueOf(onetimepass);
                    JOptionPane.showMessageDialog(this, "otp is "+onetimepass);
                    jPanel1.setVisible(false);
                    jPanel2.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(this, "No user found with this email");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String otpfield = jotp.getText();
        if (otpfield.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter an otp");
        } else {
            if (otpfield.equals(otp)) {
                jPanel2.setVisible(false);
                jPanel3.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Please Enter Correct otp");
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String newpassword = jnewpassword.getText();
        String confirmnewpassword = jconfirmpassword.getText();
        if (newpassword.isEmpty() || confirmnewpassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill all the field");
        } else {
            if (newpassword.equals(confirmnewpassword)) {
                try {
                    ResultSet rs = DBLoader.exexuteSQL("select * from user where email ='"+email+"' ");
                    if(rs.next()){
                        rs.updateString("password",newpassword);
                        rs.updateRow();
                        JOptionPane.showMessageDialog(this, "Password changed successfully!!");
                        dispose();
                    }else{
                        JOptionPane.showMessageDialog(this, "No user fouund!!");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "New Password and Confirm New Password must be same");
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_forgot_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_forgot_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jconfirmpassword;
    private javax.swing.JTextField jemail;
    private javax.swing.JTextField jnewpassword;
    private javax.swing.JTextField jotp;
    private javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
